export interface Commit {
  id:                string;
  message:           string;
  dateCreated:       string;
  author:            Author;
}

export interface Author {
  id:              string;
  name:            string;
  username:        string;
  email:           string;
}


// Generated by https://quicktype.io

export interface Release {
  id:                 number;
  version:            string;
  status:             string;
  shortVersion:       string;
  versionInfo:        VersionInfo;
  ref:                null;
  url:                null;
  dateReleased:       null;
  dateCreated:        string;
  commitCount:        number;
  deployCount:        number;
  lastDeploy:         LastDeploy;
  authors:            Author[];
}

export interface LastDeploy {
  id:           string;
  environment:  string;
  dateFinished: string;
  name:         string;
}

export interface VersionInfo {
  package:     string;
  version:     Version;
  description: string;
  buildHash:   string;
}

export interface Version {
  raw: string;
}

