import { Sound, Voice } from "./audio";
export interface Commit {
  id: string;
  message: string;
  dateCreated: string;
  author: Author;
}

export interface Author {
  id: string;
  name: string;
  username: string;
  email: string;
}

// Generated by https://quicktype.io

export interface Release {
  id: number;
  version: string;
  status: string;
  shortVersion: string;
  versionInfo: VersionInfo;
  ref: null;
  url: null;
  dateReleased: null;
  dateCreated: string;
  commitCount: number;
  deployCount: number;
  lastDeploy: LastDeploy;
  authors: Author[];
  projects: Project[];
}

export interface LastDeploy {
  id: string;
  environment: string;
  dateFinished: string;
  name: string;
}

export interface VersionInfo {
  package: string;
  version: Version;
  description: string;
  buildHash: string;
}

export interface Version {
  raw: string;
}

export interface Project {
  id: string;
  slug: string;
}

export interface MatchConfig {
  author: string;
  type: string;
  scope: string;
}

export interface Rule {
  match: Partial<MatchConfig>;
  play: Partial<RuleConfig>;
}

export interface RuleConfig {
  nickname: string;
  voice: Voice;
  sound: Sound;
  light: boolean;
}

export interface ParsedCommit {
  author: Author;
  type?: string;
  scope?: string;
  subject?: string;
}

export type AnnouncementConfig = {
  message: string;
  voice: Voice;
  sound?: Sound;
  light: boolean;
};
